PARALGO_DIR=paralgo
PARALGO_PARTS= \
	$(PARALGO_DIR)/*.tex

include $(PARALGO_DIR)/stl/Makefile.def
include $(PARALGO_DIR)/exec/Makefile.def
include $(PARALGO_DIR)/numeric/Makefile.def

GUIDE_PARTS += $(PARALGO_PARTS)

PARALGO_PDF=$(PARALGO_DIR).pdf
FINAL_PARALGO_PDF=$(FINAL_DIR)/$(PARALGO_PDF)

ALL_SLIDES_FINAL_PDF += \
	$(FINAL_PARALGO_PDF)
